//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace MemberManageSilverlight.wcfService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/MemberWCF")]
    public partial class Member : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AccountField;
        
        private string ChNameField;
        
        private System.DateTime CreateTimeField;
        
        private string EmailField;
        
        private int IDField;
        
        private string NickNameField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChName {
            get {
                return this.ChNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChNameField, value) != true)) {
                    this.ChNameField = value;
                    this.RaisePropertyChanged("ChName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfService.IWcf_Getdata")]
    public interface IWcf_Getdata {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcf_Getdata/GetAllMember", ReplyAction="http://tempuri.org/IWcf_Getdata/GetAllMemberResponse")]
        System.IAsyncResult BeginGetAllMember(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> EndGetAllMember(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcf_Getdata/CreateMember", ReplyAction="http://tempuri.org/IWcf_Getdata/CreateMemberResponse")]
        System.IAsyncResult BeginCreateMember(MemberManageSilverlight.wcfService.Member member, System.AsyncCallback callback, object asyncState);
        
        void EndCreateMember(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcf_Getdata/Delete", ReplyAction="http://tempuri.org/IWcf_Getdata/DeleteResponse")]
        System.IAsyncResult BeginDelete(int id, System.AsyncCallback callback, object asyncState);
        
        void EndDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcf_Getdata/Search", ReplyAction="http://tempuri.org/IWcf_Getdata/SearchResponse")]
        System.IAsyncResult BeginSearch(string SearchText, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> EndSearch(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcf_Getdata/Edit", ReplyAction="http://tempuri.org/IWcf_Getdata/EditResponse")]
        System.IAsyncResult BeginEdit(MemberManageSilverlight.wcfService.Member UpdateMember, System.AsyncCallback callback, object asyncState);
        
        void EndEdit(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcf_GetdataChannel : MemberManageSilverlight.wcfService.IWcf_Getdata, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Wcf_GetdataClient : System.ServiceModel.ClientBase<MemberManageSilverlight.wcfService.IWcf_Getdata>, MemberManageSilverlight.wcfService.IWcf_Getdata {
        
        private BeginOperationDelegate onBeginGetAllMemberDelegate;
        
        private EndOperationDelegate onEndGetAllMemberDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllMemberCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateMemberDelegate;
        
        private EndOperationDelegate onEndCreateMemberDelegate;
        
        private System.Threading.SendOrPostCallback onCreateMemberCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchDelegate;
        
        private EndOperationDelegate onEndSearchDelegate;
        
        private System.Threading.SendOrPostCallback onSearchCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditDelegate;
        
        private EndOperationDelegate onEndEditDelegate;
        
        private System.Threading.SendOrPostCallback onEditCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Wcf_GetdataClient() {
        }
        
        public Wcf_GetdataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Wcf_GetdataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Wcf_GetdataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Wcf_GetdataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("無法設定 CookieContainer。請確定繫結包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<GetAllMemberCompletedEventArgs> GetAllMemberCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CreateMemberCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteCompleted;
        
        public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EditCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MemberManageSilverlight.wcfService.IWcf_Getdata.BeginGetAllMember(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllMember(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> MemberManageSilverlight.wcfService.IWcf_Getdata.EndGetAllMember(System.IAsyncResult result) {
            return base.Channel.EndGetAllMember(result);
        }
        
        private System.IAsyncResult OnBeginGetAllMember(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MemberManageSilverlight.wcfService.IWcf_Getdata)(this)).BeginGetAllMember(callback, asyncState);
        }
        
        private object[] OnEndGetAllMember(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> retVal = ((MemberManageSilverlight.wcfService.IWcf_Getdata)(this)).EndGetAllMember(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllMemberCompleted(object state) {
            if ((this.GetAllMemberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllMemberCompleted(this, new GetAllMemberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllMemberAsync() {
            this.GetAllMemberAsync(null);
        }
        
        public void GetAllMemberAsync(object userState) {
            if ((this.onBeginGetAllMemberDelegate == null)) {
                this.onBeginGetAllMemberDelegate = new BeginOperationDelegate(this.OnBeginGetAllMember);
            }
            if ((this.onEndGetAllMemberDelegate == null)) {
                this.onEndGetAllMemberDelegate = new EndOperationDelegate(this.OnEndGetAllMember);
            }
            if ((this.onGetAllMemberCompletedDelegate == null)) {
                this.onGetAllMemberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllMemberCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllMemberDelegate, null, this.onEndGetAllMemberDelegate, this.onGetAllMemberCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MemberManageSilverlight.wcfService.IWcf_Getdata.BeginCreateMember(MemberManageSilverlight.wcfService.Member member, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateMember(member, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MemberManageSilverlight.wcfService.IWcf_Getdata.EndCreateMember(System.IAsyncResult result) {
            base.Channel.EndCreateMember(result);
        }
        
        private System.IAsyncResult OnBeginCreateMember(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MemberManageSilverlight.wcfService.Member member = ((MemberManageSilverlight.wcfService.Member)(inValues[0]));
            return ((MemberManageSilverlight.wcfService.IWcf_Getdata)(this)).BeginCreateMember(member, callback, asyncState);
        }
        
        private object[] OnEndCreateMember(System.IAsyncResult result) {
            ((MemberManageSilverlight.wcfService.IWcf_Getdata)(this)).EndCreateMember(result);
            return null;
        }
        
        private void OnCreateMemberCompleted(object state) {
            if ((this.CreateMemberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateMemberCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateMemberAsync(MemberManageSilverlight.wcfService.Member member) {
            this.CreateMemberAsync(member, null);
        }
        
        public void CreateMemberAsync(MemberManageSilverlight.wcfService.Member member, object userState) {
            if ((this.onBeginCreateMemberDelegate == null)) {
                this.onBeginCreateMemberDelegate = new BeginOperationDelegate(this.OnBeginCreateMember);
            }
            if ((this.onEndCreateMemberDelegate == null)) {
                this.onEndCreateMemberDelegate = new EndOperationDelegate(this.OnEndCreateMember);
            }
            if ((this.onCreateMemberCompletedDelegate == null)) {
                this.onCreateMemberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateMemberCompleted);
            }
            base.InvokeAsync(this.onBeginCreateMemberDelegate, new object[] {
                        member}, this.onEndCreateMemberDelegate, this.onCreateMemberCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MemberManageSilverlight.wcfService.IWcf_Getdata.BeginDelete(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MemberManageSilverlight.wcfService.IWcf_Getdata.EndDelete(System.IAsyncResult result) {
            base.Channel.EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((MemberManageSilverlight.wcfService.IWcf_Getdata)(this)).BeginDelete(id, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            ((MemberManageSilverlight.wcfService.IWcf_Getdata)(this)).EndDelete(result);
            return null;
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(int id) {
            this.DeleteAsync(id, null);
        }
        
        public void DeleteAsync(int id, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        id}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MemberManageSilverlight.wcfService.IWcf_Getdata.BeginSearch(string SearchText, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearch(SearchText, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> MemberManageSilverlight.wcfService.IWcf_Getdata.EndSearch(System.IAsyncResult result) {
            return base.Channel.EndSearch(result);
        }
        
        private System.IAsyncResult OnBeginSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string SearchText = ((string)(inValues[0]));
            return ((MemberManageSilverlight.wcfService.IWcf_Getdata)(this)).BeginSearch(SearchText, callback, asyncState);
        }
        
        private object[] OnEndSearch(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> retVal = ((MemberManageSilverlight.wcfService.IWcf_Getdata)(this)).EndSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchCompleted(object state) {
            if ((this.SearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCompleted(this, new SearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAsync(string SearchText) {
            this.SearchAsync(SearchText, null);
        }
        
        public void SearchAsync(string SearchText, object userState) {
            if ((this.onBeginSearchDelegate == null)) {
                this.onBeginSearchDelegate = new BeginOperationDelegate(this.OnBeginSearch);
            }
            if ((this.onEndSearchDelegate == null)) {
                this.onEndSearchDelegate = new EndOperationDelegate(this.OnEndSearch);
            }
            if ((this.onSearchCompletedDelegate == null)) {
                this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
            }
            base.InvokeAsync(this.onBeginSearchDelegate, new object[] {
                        SearchText}, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MemberManageSilverlight.wcfService.IWcf_Getdata.BeginEdit(MemberManageSilverlight.wcfService.Member UpdateMember, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEdit(UpdateMember, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MemberManageSilverlight.wcfService.IWcf_Getdata.EndEdit(System.IAsyncResult result) {
            base.Channel.EndEdit(result);
        }
        
        private System.IAsyncResult OnBeginEdit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MemberManageSilverlight.wcfService.Member UpdateMember = ((MemberManageSilverlight.wcfService.Member)(inValues[0]));
            return ((MemberManageSilverlight.wcfService.IWcf_Getdata)(this)).BeginEdit(UpdateMember, callback, asyncState);
        }
        
        private object[] OnEndEdit(System.IAsyncResult result) {
            ((MemberManageSilverlight.wcfService.IWcf_Getdata)(this)).EndEdit(result);
            return null;
        }
        
        private void OnEditCompleted(object state) {
            if ((this.EditCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditAsync(MemberManageSilverlight.wcfService.Member UpdateMember) {
            this.EditAsync(UpdateMember, null);
        }
        
        public void EditAsync(MemberManageSilverlight.wcfService.Member UpdateMember, object userState) {
            if ((this.onBeginEditDelegate == null)) {
                this.onBeginEditDelegate = new BeginOperationDelegate(this.OnBeginEdit);
            }
            if ((this.onEndEditDelegate == null)) {
                this.onEndEditDelegate = new EndOperationDelegate(this.OnEndEdit);
            }
            if ((this.onEditCompletedDelegate == null)) {
                this.onEditCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditCompleted);
            }
            base.InvokeAsync(this.onBeginEditDelegate, new object[] {
                        UpdateMember}, this.onEndEditDelegate, this.onEditCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MemberManageSilverlight.wcfService.IWcf_Getdata CreateChannel() {
            return new Wcf_GetdataClientChannel(this);
        }
        
        private class Wcf_GetdataClientChannel : ChannelBase<MemberManageSilverlight.wcfService.IWcf_Getdata>, MemberManageSilverlight.wcfService.IWcf_Getdata {
            
            public Wcf_GetdataClientChannel(System.ServiceModel.ClientBase<MemberManageSilverlight.wcfService.IWcf_Getdata> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllMember(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllMember", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> EndGetAllMember(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> _result = ((System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member>)(base.EndInvoke("GetAllMember", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateMember(MemberManageSilverlight.wcfService.Member member, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = member;
                System.IAsyncResult _result = base.BeginInvoke("CreateMember", _args, callback, asyncState);
                return _result;
            }
            
            public void EndCreateMember(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("CreateMember", _args, result);
            }
            
            public System.IAsyncResult BeginDelete(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Delete", _args, result);
            }
            
            public System.IAsyncResult BeginSearch(string SearchText, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = SearchText;
                System.IAsyncResult _result = base.BeginInvoke("Search", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> EndSearch(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member> _result = ((System.Collections.ObjectModel.ObservableCollection<MemberManageSilverlight.wcfService.Member>)(base.EndInvoke("Search", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEdit(MemberManageSilverlight.wcfService.Member UpdateMember, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = UpdateMember;
                System.IAsyncResult _result = base.BeginInvoke("Edit", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEdit(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Edit", _args, result);
            }
        }
    }
}
