//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManageSilverlight
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// RIA 應用程式的內容。
    /// </summary>
    /// <remarks>
    /// 這個內容會延伸基底，讓應用程式服務和型別
    /// 可從程式碼及 xaml 使用。
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region 擴充性方法定義

        /// <summary>
        /// 這個方法在初始化完成後會被從建構函式叫用，
        /// 而且進一步可用於的物件安裝。
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// 初始化 WebContext 類別的新執行個體。
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// 透過目前的應用程式取得已註冊為存留期物件的內容。
        /// </summary>
        /// 如果沒有目前的應用程式，則會擲回 <exception cref="InvalidOperationException">，
        /// 但不會加入任何任容，否則會加入一個以上的內容。
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
    }
}
